config/routes.rb
Rails.application.routes.draw do
  # pages
  root 'pages#index'
  get 'whywhatwho', to: 'pages#whywhatwho', as: 'whywhatwho'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact_email', to: 'pages#contact_email', as: 'contact_email'
  post 'subscribe_email', to: 'pages#subscribe_email', as: 'subscribe_email'
  get 'projects', to: 'pages#projects', as: 'projects'
  get 'projects/:custom_url', to: 'pages#project', as: 'project'
  get 'swap_locale', to: 'pages#swap_locale', as: 'swap_locale'

  resources :inco_projects
  resources :inco_findings, only: [:show, :edit, :update]
  resources :inco_processes, :inco_finals, only: [] do
    resources :inco_pictures, shallow: true
  end
end

app/models/inco_project.rb
class IncoProject < ApplicationRecord
  include IncoTranslate
  include RailsSortable::Model
  set_sortable :sort  # Indicate a sort column

  after_create :build_contents
  mount_uploader :cover_photo, CoverPhotoUploader
  # 由於custom_url取代了finding的id，所以是必須的值
  validates :custom_url, presence: true

  has_one :inco_process, dependent: :destroy
  has_one :inco_final, dependent: :destroy
  has_one :inco_finding, dependent: :destroy

  private

  def build_contents
    self.inco_process = IncoProcess.create!
    self.inco_final = IncoFinal.create!
    self.inco_finding = IncoFinding.create!
  end
end

app/controllers/inco_projects_controller.rb
class IncoProjectsController < DashboardController
  before_action :set_inco_project, only: [:show, :edit, :update, :destroy]

  # GET /inco_projects
  def index
    @inco_projects = IncoProject.order(:sort).all
  end

  # GET /inco_projects/1
  def show
  end

  # GET /inco_projects/new
  def new
    @inco_project = IncoProject.new
  end

  # GET /inco_projects/1/edit
  def edit
  end

  # POST /inco_projects
  def create
    @inco_project = IncoProject.new(inco_project_params)
    if @inco_project.save
      redirect_to @inco_project, notice: 'Inco project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /inco_projects/1
  def update
    if @inco_project.update(inco_project_params)
      redirect_to @inco_project, notice: 'Inco project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /inco_projects/1
  def destroy
    @inco_project.destroy
    redirect_to inco_projects_url, notice: 'Inco project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inco_project
    @inco_project = IncoProject.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def inco_project_params
    params.require(:inco_project).permit(:title_zh, :title_en, :description_zh,
                                         :description_en, :challenge_zh, :challenge_en,
                                         :location, :status, :partners, :dates,
                                         :services_zh, :services_en, :keywords_zh,
                                         :keywords_en, :process_title_zh,
                                         :process_title_en, :cover_photo, :inco_category,
                                         :showing, :custom_url, :site_url)
  end
end

app/views/inco_projects/_form.html.erb
<%= form_for(inco_project) do |f| %>
  <% if inco_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inco_project.errors.count, "error") %> prohibited this inco_project from being saved:</h2>

      <ul>
      <% inco_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label(:cover_photo, "封面照片") %><br>
  <%= image_tag(inco_project.cover_photo) %><br>
  <%= f.file_field :cover_photo, class: 'form-control-file' %>
  <%= f.label(:title_zh, "Chinese title") %>
  <%= f.text_field :title_zh, class: 'form-control' %><br>
  <%= f.label(:title_en, "English title") %>
  <%= f.text_field :title_en, class: 'form-control' %><br>
  <%= f.label(:inco_category, "Category") %>
  <%= f.select :inco_category, ['space', 'research', 'experience', 'communication'], class: 'form-control' %><br>
  <%= f.label(:custom_url, "Custom URL") %>
  <%= f.text_field :custom_url, class: 'form-control' %><br>
  <%= f.label(:site_url, "URL(如果專案是一個網站，可在這裡輸入網址，否則為空)") %>
  <%= f.text_field :site_url, class: 'form-control' %><br>
  <div class="form-check">
    <%= f.check_box :showing, class: 'form-check-input' %>
    <%= f.label(:showing, "Showing?", class: 'form-check-label') %>
  </div><br>
  <%= f.label(:location, "Location") %>
  <%= f.text_field :location, class: 'form-control' %><br>
  <%= f.label(:dates, "Dates") %>
  <%= f.text_field :dates, class: 'form-control' %><br>
  <%= f.label(:status, "Status") %>
  <%= f.text_field :status, class: 'form-control' %><br>
  <%= f.label(:partners, "Partners") %>
  <%= f.text_field :partners, class: 'form-control' %><br>
  <%= f.label(:keywords_zh, "Chinese Keywords(seperated by 、)") %>
  <%= f.text_field :keywords_zh, class: 'form-control' %><br>
  <%= f.label(:keywords_en, "English Keywords(seperated by 、)") %>
  <%= f.text_field :keywords_en, class: 'form-control' %><br>
  <%= f.label(:process_title_zh, "Chinese Process title") %>
  <%= f.text_field :process_title_zh, class: 'form-control' %><br>
   <%= f.label(:process_title_en, "EnglishProcess title") %>
  <%= f.text_field :process_title_en, class: 'form-control' %><br>
  <%= f.label(:services_zh, "Chinese services") %>
  <%= f.text_field :services_zh, class: 'form-control' %><br>
  <%= f.label(:services_en, "English services") %>
  <%= f.text_field :services_en, class: 'form-control' %><br>

  <%= f.label(:description_zh, "Chinese Description") %>
  <%= f.text_area(:description_zh, class: "f_editor") %>
    <%= f.label(:description_en, "English Description") %>
  <%= f.text_area(:description_en, class: "f_editor") %>
    <%= f.label(:challenge_zh, "Chinese Challenge") %>
  <%= f.text_area(:challenge_zh, class: "f_editor") %>
    <%= f.label(:challenge_en, "English Challenge") %>
  <%= f.text_area(:challenge_en, class: "f_editor") %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inco_projects/edit.html.erb
<h1>Editing Inco Project</h1>

<%= render 'form', inco_project: @inco_project %>

<%= link_to 'Show', @inco_project %> |
<%= link_to 'Back', inco_projects_path %>

app/views/inco_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inco Projects</h1>
<h5>(projects order can change by drag&drop)</h5>

<table class="table">
  <thead>
    <tr>
      <th>Project Name</th>
      <th colspan="3">ProjectContents</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody class="sortable"> <!-- sortable target -->
    <% @inco_projects.each_with_sortable_id do |inco_project, sortable_id| %>
      <tr id="<%= sortable_id %>"> <!-- Needs id tag on sorting elements -->
        <td><%= inco_project.title %></td>
        <td><%= link_to 'Process', inco_process_inco_pictures_path(inco_project.inco_process) %></td>
        <td><%= link_to 'Final', inco_final_inco_pictures_path(inco_project.inco_final) %></td>
        <td><%= link_to 'Finding', inco_finding_path(inco_project.inco_finding) %></td>
        <td><%= link_to 'Show_Project', project_path(inco_project.custom_url) %></td>
        <td><%= link_to 'Edit_Project', edit_inco_project_path(inco_project) %></td>
        <td><%= link_to 'Destroy', inco_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inco Project', new_inco_project_path %>

app/views/inco_projects/new.html.erb
<h1>New Inco Project</h1>

<%= render 'form', inco_project: @inco_project %>

<%= link_to 'Back', inco_projects_path %>

app/views/inco_projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inco_project_path(@inco_project) %> |
<%= link_to 'Back', inco_projects_path %>