config/routes.rb
Rails.application.routes.draw do
  # pages
  root 'pages#index'
  get 'whywhatwho', to: 'pages#whywhatwho', as: 'whywhatwho'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact_email', to: 'pages#contact_email', as: 'contact_email'
  post 'subscribe_email', to: 'pages#subscribe_email', as: 'subscribe_email'
  get 'projects', to: 'pages#projects', as: 'projects'
  get 'projects/:custom_url', to: 'pages#project', as: 'project'
  get 'swap_locale', to: 'pages#swap_locale', as: 'swap_locale'

  resources :inco_projects
  resources :inco_findings, only: [:show, :edit, :update]
  resources :inco_processes, :inco_finals, only: [] do
    resources :inco_pictures, shallow: true
  end
end

app/models/inco_picture.rb
class IncoPicture < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  mount_uploader :poster, PosterUploader
  belongs_to :inco_content, polymorphic: true

  include RailsSortable::Model
  set_sortable :sort  # Indicate a sort column

  def is_image?
    return false if self.file_content_type.nil?
    self.file_content_type.start_with? 'image'
  end
end

app/controllers/inco_pictures_controller.rb
class IncoPicturesController < DashboardController
  before_action :set_inco_picture, only: [:show, :edit, :update, :destroy]
  before_action :set_inco_content, only: [:index, :new, :create]

  # GET /inco_pictures
  # GET /inco_pictures.json
  def index
    @inco_pictures = @inco_content.inco_pictures.order(:sort)
  end

  # GET /inco_pictures/1
  # GET /inco_pictures/1.json
  def show
  end

  # GET /inco_pictures/new
  def new
    @inco_picture = IncoPicture.new(inco_content: @inco_content)
  end

  # GET /inco_pictures/1/edit
  def edit
  end

  # POST /inco_pictures
  # POST /inco_pictures.json
  def create
    @inco_picture = IncoPicture.new(inco_picture_params.merge(inco_content: @inco_content))

    respond_to do |format|
      if @inco_picture.save
        format.html { redirect_to @inco_picture, notice: 'Inco picture was successfully created.' }
        format.json { render :show, status: :created, location: @inco_picture }
      else
        format.html { render :new }
        format.json { render json: @inco_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inco_pictures/1
  # PATCH/PUT /inco_pictures/1.json
  def update
    respond_to do |format|
      if @inco_picture.update(inco_picture_params)
        format.html { redirect_to @inco_picture, notice: 'Inco picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @inco_picture }
      else
        format.html { render :edit }
        format.json { render json: @inco_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inco_pictures/1
  # DELETE /inco_pictures/1.json
  def destroy
    content = @inco_picture.inco_content
    back_url = content.is_a?(IncoProcess) ? inco_process_inco_pictures_url(content) :
                                            inco_final_inco_pictures_url(content)
    @inco_picture.destroy
    respond_to do |format|
      format.html { redirect_to back_url, notice: 'Inco picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inco_picture
      @inco_picture = IncoPicture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inco_picture_params
      params.require(:inco_picture).permit(:photo, :is_photo, :youtube_id, :title_color, :poster)
    end

    def set_inco_content
      @inco_content = if params[:inco_process_id].present?
                        IncoProcess.find(params[:inco_process_id])
                      else
                        IncoFinal.find(params[:inco_final_id])
                      end
    end
end

app/helpers/inco_pictures_helper.rb
module IncoPicturesHelper
  def pictures_index_path
    if @inco_picture.inco_content
      if @inco_picture.inco_content_type == 'IncoProcess'
        inco_process_inco_pictures_path(@inco_picture.inco_content)
      else
        inco_final_inco_pictures_path(@inco_picture.inco_content)
      end
    elsif params[:inco_process_id].present?
      inco_process_inco_pictures_path
    else
      inco_final_inco_pictures_path
    end
  end

  def new_picture_path
    if params[:inco_process_id].present?
      new_inco_process_inco_picture_path
    else
      new_inco_final_inco_picture_path
    end
  end

  def youtube_thumbnail(inco_picture)
    "http://img.youtube.com/vi/#{inco_picture.youtube_id}/0.jpg"
  end
end

app/views/inco_pictures/_form.html.erb
<%= form_for([@inco_content, inco_picture]) do |f| %>
  <% if inco_picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inco_picture.errors.count, "error") %> prohibited this inco_picture from being saved:</h2>

      <ul>
      <% inco_picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_color, "title color(preventing light title on light background)" %>
    <%= f.select :title_color, %w(light dark) %>
  </div>

  <div class="field">
    <%= f.label :photo, "Photo(jpg, png) or Video file(only mp4)" %>
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :poster, 'Video Poster(need it when uploading video file)' %>
    <%= f.file_field :poster %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inco_pictures/edit.html.erb
<h1>Editing Inco Picture</h1>

<%= render 'form', inco_picture: @inco_picture %>

<%= link_to 'Show', @inco_picture %> |
<%= link_to 'Back', pictures_index_path%>

app/views/inco_pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inco Pictures</h1>

<table class="table">
  <thead>
    <tr>
      <th>Photo</th>
      <th>VideoPoster</th>
      <th>title color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="sortable">  <!-- sortable target -->
    <% @inco_pictures.each_with_sortable_id do |inco_picture, sortable_id| %>
      <tr class="<%= sortable_id %>">
        <td><%= image_tag(inco_picture.is_image? ? inco_picture.photo.thumb : inco_picture.photo.video_thumb, class: "thumbnail") %></td>
        <td>
          <% if inco_picture.poster %>
          <%= image_tag(inco_picture.poster, class: "thumbnail") %>
          <% end %>
        </td>
        <td><%= inco_picture.title_color %></td>
        <td><%= link_to 'Show', inco_picture %></td>
        <td><%= link_to 'Edit', edit_inco_picture_path(inco_picture) %></td>
        <td><%= link_to 'Destroy', inco_picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inco Picture', new_picture_path %>

app/views/inco_pictures/new.html.erb
<h1>New Inco Picture</h1>

<%= render 'form', inco_picture: @inco_picture %>

<%= link_to 'Back', pictures_index_path %>

app/views/inco_pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <% if @inco_picture.is_image? %>
    <%= image_tag @inco_picture.photo %>
  <% else %>
    <%= video_tag @inco_picture.photo %>
  <% end %>
</p>

<p>
  <strong>poster:</strong>
  <% if @inco_picture.poster %>
    <%= image_tag @inco_picture.poster %>
  <% end %>
</p>

<p>
  <strong>title color</strong>
  <%= @inco_picture.title_color %>
</p>

<%= link_to 'Edit', edit_inco_picture_path(@inco_picture) %> |
<%= link_to 'Back', pictures_index_path %>