config/routes.rb
Rails.application.routes.draw do
  # pages
  root 'pages#index'
  get 'whywhatwho', to: 'pages#whywhatwho', as: 'whywhatwho'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact_email', to: 'pages#contact_email', as: 'contact_email'
  post 'subscribe_email', to: 'pages#subscribe_email', as: 'subscribe_email'
  get 'projects', to: 'pages#projects', as: 'projects'
  get 'projects/:custom_url', to: 'pages#project', as: 'project'
  get 'swap_locale', to: 'pages#swap_locale', as: 'swap_locale'

  resources :inco_projects
  resources :inco_findings, only: [:show, :edit, :update]
  resources :inco_processes, :inco_finals, only: [] do
    resources :inco_pictures, shallow: true
  end
end

app/views/pages/partials/_comment_form.html.erb
<%= form_tag(contact_email_path, method: "post") do %>
  <ul class="contact_list col-md-8 col-xs-12 bootstrap_default">
    <li>M. +886 920 213 466</li>
    <li>W. in-co.studio</li>
    <li>E. hi@in-co.studio</li>
    <li>A. 台北市中山區中山北路一段 98 號 3 樓</li>
    <li>
      <%= text_field_tag(:email, '', {placeholder: 'Email Address', class: 'contact_email'})%>
    </li>
    <li>
      <%= text_area_tag(:content, '', {placeholder: "Let's have a discussion !", class: 'contact_textarea'})%>
    </li>
    <li>
      <div class="btn_underline">
        <span></span>
        <%= submit_tag("Submit", {id: 'submit_btn', class: 'submit_btn'}) %>
      </div>
    </li>
  </ul>
<% end %>

app/views/pages/partials/_contact.html.erb
<!-- SECTION05 -->
<div class="section contact_map_section" id="section5">
  <div class="contact_map" id="map"></div>
  <div class="contact_mask"></div>
  <div class="container_info">
    <div class="i_title">Contact</div>
    <p class="contact_des">Let's be crazy together!</p>

    <%= render "pages/partials/comment_form" %>
  </div>
  <script>

  var center_lat = ($(window).width() < 768) ? 121.5190056 : 121.5120;
  function initMap() {
    // Create a new StyledMapType object, passing it an array of styles,
    // and the name to be displayed on the map type control.
    var styledMapType = new google.maps.StyledMapType(
      [{
          "featureType": "administrative.land_parcel",
          "elementType": "labels",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "landscape.man_made",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "landscape.natural",
          "elementType": "geometry.fill",
          "stylers": [{
            "color": "#e8e7db"
          }]
        },
        {
          "featureType": "poi",
          "elementType": "geometry.fill",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "poi",
          "elementType": "labels",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "poi.business",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "poi.park",
          "elementType": "labels.text",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "road",
          "elementType": "geometry.stroke",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "road.arterial",
          "elementType": "geometry.fill",
          "stylers": [{
              "color": "#ccd0bd"
            },
            {
              "weight": 6
            }
          ]
        },
        {
          "featureType": "road.arterial",
          "elementType": "labels.text.fill",
          "stylers": [{
            "color": "#aeaa82"
          }]
        },
        {
          "featureType": "road.arterial",
          "elementType": "labels.text.stroke",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "road.highway",
          "elementType": "geometry.fill",
          "stylers": [{
            "color": "#b5ba9e"
          }]
        },
        {
          "featureType": "road.highway",
          "elementType": "geometry.stroke",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "road.highway",
          "elementType": "labels",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "road.local",
          "elementType": "geometry.fill",
          "stylers": [{
              "color": "#d5d7c8"
            },
            {
              "weight": 2.5
            }
          ]
        },
        {
          "featureType": "road.local",
          "elementType": "labels.text",
          "stylers": [{
            "color": "#aba77c"
          }]
        },
        {
          "featureType": "road.local",
          "elementType": "labels.text.fill",
          "stylers": [{
            "color": "#b9b695"
          }]
        },
        {
          "featureType": "road.local",
          "elementType": "labels.text.stroke",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "transit",
          "elementType": "labels.text.fill",
          "stylers": [{
            "color": "#837d54"
          }]
        },
        {
          "featureType": "transit",
          "elementType": "labels.text.stroke",
          "stylers": [{
            "visibility": "off"
          }]
        },
        {
          "featureType": "transit.line",
          "elementType": "geometry",
          "stylers": [{
            "weight": 1.5
          }]
        },
        {
          "featureType": "transit.station.bus",
          "elementType": "labels",
          "stylers": [{
            "visibility": "off"
          }]
        }
      ], { name: 'Styled Map' });

    // Create a map object, and include the MapTypeId to add
    // to the map type control.
    var map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: 25.049427, lng: center_lat },
      zoom: 16,
      mapTypeControlOptions: {
        mapTypeIds: []
      },
      streetViewControl: false,
      scrollwheel: false,
      navigationControl: false,
      mapTypeControl: false,
      scaleControl: false,
      draggable: true
    });

    var marker = new google.maps.Marker({
      position: { lat: 25.049427, lng: 121.521130 },
      map: map,
      title: 'IN-CO Studio!'
    });

    //Associate the styled map with the MapTypeId and set it to display.
    map.mapTypes.set('styled_map', styledMapType);
    map.setMapTypeId('styled_map');
  }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= Settings.google_map.key %>&callback=initMap">
  </script>
</div>
<!--END SECTION05-->

app/views/pages/partials/_footer.html.erb
<!-- SECTION06 -->
<div class="section" id="section6">
  <div class="tag_pc">
    <%= render 'pages/partials/menu', parent_partial: 'footer' %>
  </div>
  <div class="tag_mobile">
    <%= render 'pages/partials/menu_mobile', parent_partial: 'footer' %>
  </div>
</div>
<!--END SECTION06-->

app/views/pages/partials/_header.html.erb
<div id="navbar_mobile"></div>
<div class="logo">
  <h1><%= link_to 'INCO', root_path %></h1>
</div>
<div class="lan">
  <% if I18n.locale == :zh %>
    <%= link_to 'EN', swap_locale_path(lang: :en) %>
  <% else %>
    <%= link_to '繁中', swap_locale_path(lang: :zh) %>
  <% end %>
</div>
<div id="menu">
  <span></span>
  <span></span>
  <span></span>
</div>
<nav>
  <div class="tag_pc">
    <%= render 'pages/partials/menu', parent_partial: 'header' %>
  </div>
  <div class="tag_mobile">
    <%= render 'pages/partials/menu_mobile', parent_partial: 'header' %>
  </div>
</nav>

app/views/pages/partials/_menu.html.erb
<ul class="container">
  <!-- create the menu switch -->
  <% if parent_partial == 'header' %>
    <div class="menuon">
      <span></span>
      <span></span>
      <span></span>
    </div>
  <% end %>

  <li class="nav_right col-sm-offset-1 col-md-5 col-xs-12">
    <h1>
      <%= link_to whywhatwho_path do %>
        <span>WHY / WHAT / WHO</span>
      <% end %>
    </h1>
    <h1 id='middle_link'>
      <%= link_to projects_path do %>
          <span>PROJECTS</span>
        <% end %>
    </h1>
    <h1>
      <%= link_to contact_path do %>
          <span>CONTACT</span>
        <% end %>
    </h1>
  </li>
  <li class="nav_left col-sm-offset-1 col-md-5 col-xs-11">
    <ul>
      <li class="nav_name">
        <%= image_tag 'logo.png' %>
        <span class="nav_sns"><a target="_blank" href="https://www.instagram.com/inco.studio/ ">ig:inco.studio</a></span>
      </li>
      <li class="nav_info">O. 886 2 2562 7402
        <br/>W. in-co.studio
        <br/>A. 台北市中山區中山北路一段 135 巷 36 號 3 樓
      </li>
      <li class="nav_email">
        <%= form_tag(subscribe_email_path, id: "subscribe_form") do %>
          <!-- <input type="text" placeholder="Your Email"> -->
          <%= text_field_tag(:email_subs, nil, placeholder: "Your Email") %>
          <button type="submit" value="Submit">subscribe</button>
        <% end %>
      </li>
    </ul>
  </li>
</ul>
<footer>
  <%= link_to 'EN', swap_locale_path(lang: :en) %> | <%= link_to '繁中', swap_locale_path(lang: :zh) %>
  <br/> 2018 in-co copyright
</footer>

app/views/pages/partials/_menu_mobile.html.erb
<div class="container mobile_menu">
  <% if parent_partial == 'header' %>
    <div class="menuon">
      <span></span>
      <span></span>
      <span></span>
    </div>
  <% end %>
  <div class="col-xs-12">
    <div class="footer_logo">
      <span class="nav_sns"><a target="_blank" href="https://www.instagram.com/inco.studio/ ">ig:inco.studio</a></span>
    </div>

    <div class="links">
      <h1>
        <%= link_to whywhatwho_path do %>
          <span>WHY / WHAT / WHO</span>
        <% end %>
      </h1>
      <h1 id='middle_link'>
        <%= link_to projects_path do %>
            <span>PROJECTS</span>
          <% end %>
      </h1>
      <h1>
        <%= link_to contact_path do %>
            <span>CONTACT</span>
          <% end %>
      </h1>
    </div>

    <div class="info">
      <p class="nav_info">
        O. 886 2 2562 7402<br>
        W. in-co.studio<br>
        A. 台北市中山區中山北路一段 135 巷 36 號 3 樓<br>
      </p>
      <div class="nav_email">
        <%= form_tag subscribe_email_path, id: "subscribe_form" do %>
          <%= text_field_tag(:email, nil, placeholder: "Your Email") %>
          <button type="btn submit" form="subscribe_form" value="Submit">subscribe</button>
        <% end %>
      </div>
    </div>

    <div class="footer">
      <h4>2O18 in-co copyright</h4>
    </div>
  </div>
</div>

app/views/pages/partials/_project_mobile.html.erb
<div class="container-fluid" id="project_container">
  <!-- SECTION01 -->
  <div id="section1">
    <div class="heros">
      <%= image_tag @project.cover_photo %>
      <div class="head_line">
        <h3>
          <%= link_to 'Projects', projects_path %>
          /
          <%= link_to @project.inco_category, projects_path(:q => @project.inco_category) %>
        </h3>
        <h1><%= @project.title %></h1>
      </div>
    </div>
    <article>
      <%=raw @project.description %>
    </article>
  </div>

  <div class="project_section02">
    <h3 class="project_title project_title02"><span>O1</span>OVERVIEW</h3>

    <ul class="project_list">
      <li class="col-md-6 col-xs-12 bootstrap_default">Location<span><%= @project.location %></span></li>
      <li class="col-md-6 col-xs-12 bootstrap_default">Dates<span><%= @project.dates %></span></li>
      <li class="col-md-6 col-xs-12 bootstrap_default">Status<span><%= @project.status %></span></li>
      <li class="col-md-6 col-xs-12 bootstrap_default">Services<span><%= @project.services %></span></li>
      <li class="col-md-6 col-xs-12 bootstrap_default">Partners<span><%= @project.partners %></span></li>
    </ul>

    <% if @project.site_url.present? %>
      <%= link_to 'Go to site', @project.site_url, { class: 'link_out' } %>
    <% end %>

    <div class="tag_mobile">
      <div class="widget-title">
        <span><%=raw @project.challenge %></span>
      </div>
    </div>

    <ul class="project_keyword">
      <li><span>KEYWORDS</span>
        <% @project.keywords.split('、').each do |keyword| %>
          <a href="javascript:;">● <%= keyword %></a>
        <% end %>
      </li>
    </ul>
  </div>


  <div id="section3">
    <h3 class="project_title02">
      <span>O2</span>FINAL
    </h3>
    <div class="final_content">
      <% @final.inco_pictures.each do |pic| %>
        <div class="final_pic">
          <% if pic.is_image? %>
            <%= image_tag pic.photo %>
          <% else %>
            <%= video_tag pic.photo, controls: true, autobuffer: true, poster: pic.poster %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>



  <div id="section4">
    <div class="project_title02">
      <h3><span>03</span>PROCESS</h3>
      <h2><%= @project.process_title %></h2>
    </div>

    <div id="video_for_mobile">
      <% @process.inco_pictures.each do |pic| %>
        <div>
          <% if pic.is_image? %>
            <%= image_tag pic.photo %>
          <% else %>
            <%= video_tag pic.photo, controls: true, autobuffer: true, poster: pic.poster %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div id="section5">
    <h3 class="project_title02">
      <span>O4</span>FINDINGS
    </h3>
    <article>
      <%=raw @project.inco_finding.description %>
    </article>
  </div>

  <div class="section6">
      <h3 class="project_title02">
        <span>O5</span>YOUR TURN
      </h3>
      <h2>分享你的想法?</h2>
      <p>in-co 很希望可以了解你的想法，很希望得到你的回信 :)</p>
      <%= form_tag contact_email_path do %>
        <%= text_field_tag(:email, '', {placeholder: 'Email Address', class: 'contact_email'})%>
        <%= text_area_tag(:content, '', {placeholder: "Let's have a discussion !", class: 'contact_textarea'})%>
        <%= submit_tag("SUBMIT", {id: 'submit_btn'}) %>
      <% end %>
  </div>

</div>

app/views/pages/partials/_project_pc.html.erb
<!-- SECTION01 -->
<div class="section project_section01" id="section0">
  <div class="container col-md-offset-2 col-md-8">
    <h3>
      <%= link_to 'PROJECTS', projects_path %>
      /
      <%= link_to @project.inco_category, projects_path(:q => @project.inco_category) %>
    </h3>
    <h1><%= @project.title %></h1>
    <article class="tag_pc">
      <%=raw @project.description %>
    </article>
  </div>
</div>

<!-- SECTION02 -->
<div class="section project_section02" id="section1">
  <div class="container">
    <div class="col-md-offset-1 col-md-10">

      <div class="tag_pc">
        <div class="project_des">
        CHALLENGE
        </div>
        <div class="widget-title">
          <span><%=raw @project.challenge %></span>
        </div>
      </div>

      <div class="project_title02">
        <span>O1</span>OVERVIEW
      </div>
      <ul class="project_list">
        <li class="col-md-6 col-xs-12 bootstrap_default">Location<span><%= @project.location %></span></li>
        <li class="col-md-6 col-xs-12 bootstrap_default">Dates<span><%= @project.dates %></span></li>
        <li class="col-md-6 col-xs-12 bootstrap_default">Status<span><%= @project.status %></span></li>
        <li class="col-md-6 col-xs-12 bootstrap_default">Services<span><%= @project.services %></span></li>
        <li class="col-md-6 col-xs-12 bootstrap_default">Partners<span><%= @project.partners %></span></li>
      </ul>

      <% if @project.site_url.present? %>
        <%= link_to 'Go to site', @project.site_url, {class: 'link_out', target: "_blank"} %>
      <% end %>

      <div class="tag_mobile">
        <div class="widget-title">
          <span><%=raw @project.challenge %></span>
        </div>
      </div>

      <ul class="project_keyword">
        <li><span>KEYWORDS</span>
          <% @project.keywords.split('、').each do |keyword| %>
            <a href="javascript:;">● <%= keyword %></a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!--END SECTION02-->

<!-- SECTION03 -->
<div class="section project_section03" id="section2">
  <div class="container">
    <div id="final_title" class="tag_pc">
      <h1>02</h1>
      <h3>FINAL</h3>
    </div>
  </div>
  <div class="final_content">
    <% @final.inco_pictures.each do |pic| %>
      <div class="final_pic" title_color="<%= pic.title_color %>">
        <% if pic.is_image? %>
          <%= image_tag pic.photo %>
        <% else %>
          <%= video_tag pic.photo, controls: true, autobuffer: true, poster: pic.poster %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<!--END SECTION03-->

<!-- SECTION04 -->
<div class="section project_section04" id="section3">
  <div class="container">

    <div class="row">
      <div class="col-md-offset-1 col-md-9">
        <ul id="video_for" class="slick video_for">
          <% @process.inco_pictures.each do |pic| %>
            <div>
              <% if pic.is_image? %>
                <%= image_tag pic.photo %>
              <% else %>
                <%= video_tag pic.photo, controls: true, autobuffer: true, poster: pic.poster %>
              <% end %>
            </div>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="tag_pc process_title">
      <div class="col-md-offset-1 col-md-1">
        <h3 class="project_title02 project_title03"><span>O3</span>PROCESS</h3>
      </div>
      <div class="col-md-3">
        <h2><%= @project.process_title %></h2>
      </div>
      <div class="col-md-5">
        <div id="video_nav">
          <% @process.inco_pictures.each do |pic| %>
            <div class="slick_nav">
              <%= image_tag(pic.is_image? ? pic.photo.thumb : pic.photo.video_thumb) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!--END SECTION04-->

<!-- SECTION05 -->
<div class="section project_section05" id="section4">
  <div class="alpha_bg"></div>
  <div class="container">
    <div class="project_title02 col-md-offset-1 col-md-2 col-xs-12">
      <span>O4</span>FINDINGS
    </div>
    <div class="col-md-7">
      <article data-simplebar class="finding_article col-md-7">
        <%=raw @project.inco_finding.description %>
      </article>
    </div>
  </div>
</div>
<!--END SECTION05-->

<!-- SECTION06 -->
<div class="section project_section06" id="section5">
  <div class="container">
    <div class="row">
      <div class="project_title02 col-md-offset-1 col-md-2 col-xs-12">
        <span>O5</span>YOUR TURN
      </div>
        <%= form_tag contact_email_path, class: "col-md-9 col-xs-12" do %>
      <ul class="contact_list">
        <li>分享你的想法?</li>
        <li>in-co 很希望可以了解你的想法，很希望得到你的回信 :)</li>
        <li>
          <%= text_field_tag(:email, '', {placeholder: 'Email Address', class: 'contact_email'})%>
        </li>
        <li>
          <%= text_area_tag(:content, '', {placeholder: "Let's have a discussion !", class: 'contact_textarea'})%>
        </li>
        <li>
          <div class="btn_underline">
            <span></span>
            <%= submit_tag("SUBMIT", {id: 'submit_btn', class: 'submit_btn'}) %>
          </div>
        </li>
      </ul>
        <% end %>
    </div>
  </div>
</div>
<!--END SECTION06-->

<%= render "pages/partials/footer" %>

app/views/pages/partials/_projects.html.erb
<!-- SECTION03 -->
<div class="section" id="section2">
  <div class="container">
    <div class="col-sm-offset-1 col-md-9 col-xs-12">
      <h1 class="title title_project">Projects</h1>
      <h3 id="project_category">
        <%= link_to '', projects_path %>
      </h3>
      <div id="inco_projects">
        <% @projects.each do |project| %>
          <div class="project" category="<%= project.inco_category %>">
            <h3><%= link_to project.title, project_path(project.custom_url) %></h3>
            <%= image_tag project.cover_photo, class: 'project_cover' %>
            <%= link_to project_path(project.custom_url) do %>
            <div class="mask"></div>
            <% end %>
          </div>
        <% end %>
      </div>
      <h4><%= link_to 'MORE PROJECTS', projects_path %></h4>
    </div>
  </div>
</div>
<!--END SECTION03-->

app/views/pages/partials/_team.html.erb
<!-- SECTION04 -->
<div class="section " id="section3">
  <div class="container">
    <div id="vue-team" class="col-sm-offset-1 col-xs-12 col-md-10">
      <div class="i_title">Who are in-co ?</div>
      <%=raw t('whywhatwho.team.we') %>
      <p class="designer_des">in-co is a(n)
        <span id="js-rotating"><%= t('whywhatwho.team.description') %></span>
      </p>

      <%= render "pages/partials/team_modal" %>
      <% team_members.each do |member| %>
        <div class="designer_list col-xs-12 col-md-3">
          <div class="designer_photo col-xs-7 col-md-12" @click="openModal('<%= member[:short] %>')">
            <span class="mask"><%= image_tag member[:photo_hover] %></span>
            <%= image_tag(member[:photo], alt: member[:name]) %>
          </div>
          <div class="designer_title col-xs-5 col-md-12">
            <div class="designer_name" @click="openModal('<%= member[:short] %>')">
              <span><%= member[:name] %></span>
            </div>
            <h4 class="designer_job"><%= member[:title] %></h4>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>
<!--END SECTION04-->

app/views/pages/partials/_team_modal.html.erb
<transition name="fade">
  <div class="team-modal" :class="target" v-show="modalOpened">
      <div class="alpha-mask"></div>
      <div class="modal-body">
        <div class="close-btn" @click="closeModal()">&times;</div>

        <div class="dot"></div>

        <h1>{{ members[target].name }}</h1>
        <h3>{{ members[target].title }}</h3>
        <div class="educations">
          <div class="education"
                v-for="edu in members[target].education"
                :key="edu.index">
            <h3 class="school">{{ edu.school }}</h3>
            <h3 class="degree font-gray">{{ edu.degree }}</h3>
            <h3 class="year font-gray">{{ edu.year }}</h3>
          </div>
        </div>
        <div class="experieces">
          <div class="experiece"
                v-for="exp in members[target].experience"
                :key="exp.index">
            <div class="col-1st">{{ exp.col1 }}</div>
            <div class="col-2nd font-gray">{{ exp.col2 }}</div>
            <div class="col-3rd font-gray">{{ exp.col3 }}</div>
            <div class="col-4th font-gray">{{ exp.col4 }}</div>
          </div>
        </div>
      </div>
  </div>
</transition>

app/views/pages/partials/_what.html.erb
<!-- SECTION02 -->
<div class="section" id="section1">
  <div class="container">
    <div class="col-sm-offset-1 col-xs-12 col-md-10" id="offers">
      <h1 class="i_title">What in-co offers ?</h1>
      <div class="row">
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.design_research.title') %></h3>
          <p><%= t('whywhatwho.expertises.design_research.description') %></p>
        </div>
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.research_design.title') %></h3>
          <p><%= t('whywhatwho.expertises.research_design.description') %></p>
        </div>
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.participatory.title') %></h3>
          <p><%= t('whywhatwho.expertises.participatory.description') %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.planning.title') %></h3>
          <p><%= t('whywhatwho.expertises.planning.description') %></p>
        </div>
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.spatial.title') %></h3>
          <p><%= t('whywhatwho.expertises.spatial.description') %></p>
        </div>
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.scale.title') %></h3>
          <p><%= t('whywhatwho.expertises.scale.description') %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.disciplinary.title') %></h3>
          <p><%= t('whywhatwho.expertises.disciplinary.description') %></p>
        </div>
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.branding.title') %></h3>
          <p><%= t('whywhatwho.expertises.branding.description') %></p>
        </div>
        <div class="col-md-4 offer">
          <h3><%= t('whywhatwho.expertises.o2o.title') %></h3>
          <p><%= t('whywhatwho.expertises.o2o.description') %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<!--END SECTION02-->

app/views/pages/partials/_youtube_iframe.html.erb
<iframe src="https://www.youtube.com/embed/<%= youtube_id %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>