config/routes.rb
Rails.application.routes.draw do
  # pages
  root 'pages#index'
  get 'whywhatwho', to: 'pages#whywhatwho', as: 'whywhatwho'
  get 'contact', to: 'pages#contact', as: 'contact'
  post 'contact_email', to: 'pages#contact_email', as: 'contact_email'
  post 'subscribe_email', to: 'pages#subscribe_email', as: 'subscribe_email'
  get 'projects', to: 'pages#projects', as: 'projects'
  get 'projects/:custom_url', to: 'pages#project', as: 'project'
  get 'swap_locale', to: 'pages#swap_locale', as: 'swap_locale'

  resources :inco_projects
  resources :inco_findings, only: [:show, :edit, :update]
  resources :inco_processes, :inco_finals, only: [] do
    resources :inco_pictures, shallow: true
  end
end

app/models/inco_finding.rb
class IncoFinding < ApplicationRecord
  include IncoTranslate
  mount_uploader :cover_photo, CoverPhotoUploader
  belongs_to :inco_project
end

app/controllers/inco_findings_controller.rb
class IncoFindingsController < ApplicationController
  before_action :set_inco_finding, only: [:show, :edit, :update, :destroy]

  # GET /inco_findings
  # GET /inco_findings.json
  def index
    @inco_findings = IncoFinding.all
  end

  # GET /inco_findings/1
  # GET /inco_findings/1.json
  def show
  end

  # GET /inco_findings/new
  def new
    @inco_finding = IncoFinding.new
  end

  # GET /inco_findings/1/edit
  def edit
  end

  # POST /inco_findings
  # POST /inco_findings.json
  def create
    @inco_finding = IncoFinding.new(inco_finding_params)

    respond_to do |format|
      if @inco_finding.save
        format.html { redirect_to @inco_finding, notice: 'Inco finding was successfully created.' }
        format.json { render :show, status: :created, location: @inco_finding }
      else
        format.html { render :new }
        format.json { render json: @inco_finding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inco_findings/1
  # PATCH/PUT /inco_findings/1.json
  def update
    respond_to do |format|
      if @inco_finding.update(inco_finding_params)
        format.html { redirect_to @inco_finding, notice: 'Inco finding was successfully updated.' }
        format.json { render :show, status: :ok, location: @inco_finding }
      else
        format.html { render :edit }
        format.json { render json: @inco_finding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inco_findings/1
  # DELETE /inco_findings/1.json
  def destroy
    @inco_finding.destroy
    respond_to do |format|
      format.html { redirect_to inco_findings_url, notice: 'Inco finding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inco_finding
      @inco_finding = IncoFinding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inco_finding_params
      params.require(:inco_finding).permit(:cover_photo, :description_zh, :description_en)
    end
end

app/views/inco_findings/_form.html.erb
<%= form_for(inco_finding) do |f| %>
  <% if inco_finding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inco_finding.errors.count, "error") %> prohibited this inco_finding from being saved:</h2>

      <ul>
      <% inco_finding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cover_photo %>
    <%= f.file_field :cover_photo %>
  </div>

  <div class="field">
    <%= f.label :description_zh %>
    <%= f.text_area :description_zh, class: "f_editor" %>
  </div>

  <div class="field">
    <%= f.label :description_en %>
    <%= f.text_area :description_en, class: "f_editor" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inco_findings/edit.html.erb
<h1>Editing Inco Finding</h1>

<%= render 'form', inco_finding: @inco_finding %>

<%= link_to 'Show', @inco_finding %>

app/views/inco_findings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cover photo:</strong><br>
  <%= image_tag @inco_finding.cover_photo %>
</p>

<p>
  <strong>Description zh:</strong><br>
  <%=raw @inco_finding.description_zh %>
</p>

<p>
  <strong>Description en:</strong><br>
  <%=raw @inco_finding.description_en %>
</p>

<%= link_to 'Edit', edit_inco_finding_path(@inco_finding) %> |
<%= link_to 'Back', inco_projects_path %>